services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # maybe use in the future?
    # user: changeme_uid:changeme_gid
    ports:
      - "8096:8096"  # Map Jellyfin port from container to host
    networks:
      - app_network
    volumes:
      - ${PATH_TO_JELLYFIN_CONFIG}:/config
      # - ${PATH_TO_CACHE}:/cache
      - type: bind
        source: ${PATH_TO_MEDIA}
        target: /media
      # - type: bind
        # source: /path/to/media2
        # target: /media2
        # read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
        # source: /path/to/fonts
        # target: /usr/local/share/fonts/custom
        # read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://rasmovidas.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${PATH_TO_NGINX_CONFIG}:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"    # Map port 80 on the host to port 80 in the container
    networks:
      - app_network
    depends_on:
      - jellyfin
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
